name: Test GitHub Action
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: typos-action
      uses: crate-ci/typos@v1.0.4

    - name: Prepare file with mistakes.
      run: echo "Finallizes" > file.txt
    - name: Test force pass with mistakes
      continue-on-error: true
      uses: ./
      with:
        files: ./file.txt

    - name: Prepare file with no mistakes.
      run: echo "Finalizes" > file.txt
    - name: Test pass with no mistakes
      uses: ./
      with:
        files: ./file.txt